export const ADD_MOVEMENT_SUCCESS = 'ADD_MOVEMENT_SUCCESS';
export const UPDATE_MOVEMENT_SUCCESS = 'ADD_MOVEMENT_SUCCESS';
export const DELETE_MOVEMENT_SUCCESS = 'DELETE_MOVEMENT_SUCCESS';
export const LOAD_MOVEMENTS_SUCCESS = 'LOAD_MOVEMENTS_SUCCESS';
