export const ADD_MOVEMENT_SUCCESS = 'ADD_MOVEMENT_SUCCESS';
export const CREATE_MOVEMENT_SUCCESS = 'CREATE_MOVEMENT_SUCCESS';
export const UPDATE_MOVEMENT_SUCCESS = 'UPDATE_MOVEMENT_SUCCESS';
export const DELETE_MOVEMENT_SUCCESS = 'DELETE_MOVEMENT_SUCCESS';
export const LOAD_MOVEMENTS_SUCCESS = 'LOAD_MOVEMENTS_SUCCESS';

export const ADD_EXERCISETYPE_SUCCESS = 'ADD_EXERCISETYPE_SUCCESS';
export const UPDATE_EXERCISETYPE_SUCCESS = 'UPDATE_EXERCISETYPE_SUCCESS';
export const DELETE_EXERCISETYPE_SUCCESS = 'DELETE_EXERCISETYPE_SUCCESS';
export const LOAD_EXERCISETYPES_SUCCESS = 'LOAD_EXERCISETYPES_SUCCESS';
